### ISSUE TITLE
syntax error, unexpected '$data' (T_VARIABLE), expecting function (T_FUNCTION)

### ISSUE THREAD

**Issue by hendisusanto** [rizalafani/rajaongkirlaravel#5]
Maaf om, mau tanya.
Kenapa ya saat ingin mengambil data, terjadi kesalahan:

**syntax error, unexpected '$data' (T_VARIABLE), expecting function (T_FUNCTION)**

*semua langkah pada tutorial sudah dilakukan dg benar.
*di Config\App juga sudah ditambahkan providers sama aliasnya.

ini Controller nya:
` <?php `
` namespace App\Http\Controllers; `
` use Illuminate\Http\Request; `
` use RajaOngkir; `
` `
` class OngkirController extends Controller `
` { `
`     $data = RajaOngkir::Provinsi()->all(); `
`     print_r($data); `
` } `
Terimakasih

**Comment by rizalafani** [comment]
Itu kode ente harusnya dimasukin di dalam function bro...

**Comment by hendisusanto** [comment]
Oiya gan maap. Terlalu banyak percobaan & belum ada yg jadi, sampe error otak. xD

**Comment by hendisusanto** [comment]
Btw ane pake Laravel 5.3 gan, mau tanya juga udah pernah dicoba di laravel 5.3 kah?
