### ISSUE TITLE
J&T ?

### ISSUE THREAD

**Issue by webowodev** [rizalafani/rajaongkirlaravel#6]
Untuk ekspedisi J&T belum tersedia yah ?
atau di rajaongkir untuk akun standard hanya ada 3 pilihan ekspedisi ?

**Comment by muhammad-ihsan** [comment]
@daemswibowo akun starter di [rajaongkir](https://rajaongkir.com/dokumentasi) saat ini hanya support 3 kurir pengiriman om

**Comment by webowodev** [comment]
@muhammad-ihsan kalo premium ?

**Comment by muhammad-ihsan** [comment]
bisa langsung di cek di rajaongkirnya loh bang @daemswibowo

**Comment by stevangoldduck** [comment]
close aja atu
